modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/CerbonXD/BetterTotemOfUndying/issues" #optional

[[mods]] #mandatory
modId="better_totem_of_undying" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Totem Of Undying" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-totem-of-undying" #optional
logoFile="logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="CerbonXD" #optional

#mandatory
description='''
Use the link above to see the whole mod description.
'''

[[dependencies.better_totem_of_undying]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.better_totem_of_undying]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
